using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BulletScript : MonoBehaviour
{
    public float speed = 5f;
    public float deactivate_Timer = 12f;
    // Start is called before the first frame update
    void Start()
    {
        Invoke("DeactivateGameObject",deactivate_Timer);
    }

    // Update is called once per frame
    void Update()
    {
        move();
    }
     void move()
    {
        Vector3 temp = transform.position;
        temp.x += speed * Time.deltaTime;
        transform.position = temp;
    }
    void DeactivateGameObject()
    {
        gameObject.SetActive(false);
        Destroy(gameObject);
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        Destroy(other);
        Destroy(gameObject);
    }

}
